server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:80/loki/api/v1/push
    tenant_id: docker

scrape_configs:
  - job_name: docker_log_scrape
    docker_sd_configs:
        - host: unix:///var/run/docker.sock
          refresh_interval: 10s
    relabel_configs:
      - target_label: 'source'
        replacement: 'promtail'

      - source_labels: [ '__meta_docker_container_label_com_docker_compose_project' ]
        target_label: 'compose_project'

      - source_labels: [ '__meta_docker_container_label_com_docker_compose_service' ]
        target_label: 'compose_service'

      - source_labels: [ '__meta_docker_container_name' ]
        regex: '/(.*)'
        target_label: 'container_name'

      - source_labels: [ '__meta_docker_container_id' ]
        target_label: 'container_id'

      - source_labels: [ '__meta_docker_network_ip' ]
        target_label: 'container_ip'