name: deploy docker-compose
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        uses: ./.github/actions/deploy/compose
        with:
          ssh_private_key: ${{ secrets.WLGDEV_SSH_PRIVATE_KEY }}
          ssh_private_host: ${{ secrets.WLGDEV_SSH_PRIVATE_HOST }}
          ssh_private_port: ${{ secrets.WLGDEV_SSH_PRIVATE_PORT }}
          ssh_private_user: ${{ secrets.WLGDEV_SSH_PRIVATE_USER }}
          delete_before_deploy:
            ./src
            ./docs
          target:
            monitor:grafana:3000
          env:
            GRAFANA_DEFAULT_DOMAIN=monitor.wlg.tv