# File .github/workflows/publish-release.yml

# Runs on creating a new release tag (when this release marked as published),
# this workflow publishes artifact and does increment the next SNAPSHOT version

name: publish RELEASE
on:
  release:
    types:
      - published

jobs:
  repository: # SERVICE LEVEL - CHECK AND SHARE VARIABLES
    if: ${{ !startsWith(github.repository, 'wlgdev/template-') }}
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.validate.outputs.type }}
      language: ${{ steps.validate.outputs.language }}
      environment: ${{ steps.validate.outputs.environment }}
    env:
      REPOSITORY_TYPE:     $(jq -r '.repository.custom_properties.type     | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
      REPOSITORY_LANGUAGE: $(jq -r '.repository.custom_properties.language | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
    steps:
      - name: validate repository type
        id: validate
        run: |
          echo "repository type:     ${{ env.REPOSITORY_TYPE }}"
          echo "repository language: ${{ env.REPOSITORY_LANGUAGE }}"
          echo "type=${{ env.REPOSITORY_TYPE }}" >> $GITHUB_OUTPUT
          echo "language=${{ env.REPOSITORY_LANGUAGE }}" >> $GITHUB_OUTPUT
          echo "environment=PRODUCTION" >> $GITHUB_OUTPUT

  deploy:
    environment: ${{ needs.repository.outputs.environment }}
    needs:
      - repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        id: deploy
        uses: ./.github/actions/deploy/compose/traefik
        with:
          ssh_private_key:  ${{ secrets.WLGDEV_SSH_PRIVATE_KEY }}
          ssh_private_host: ${{ secrets.WLGDEV_SSH_PRIVATE_HOST }}
          ssh_private_port: ${{ secrets.WLGDEV_SSH_PRIVATE_PORT }}
          ssh_private_user: ${{ secrets.WLGDEV_SSH_PRIVATE_USER }}
          delete_before_deploy:
            ./src
            ./docs
          compose_file: './docker-compose.yml'
          target:
            monitor:grafana:3000
          env:
            GRAFANA_DEFAULT_DOMAIN=monitor.wlg.tv